board/urls.py
from django.urls import path
from . import views

#http://localhost/board/
app_name = 'board'
urlpatterns = [
    path('', views.board_list, name='board_list'),
    path('write/', views.board_write, name='board_write'),
    path('detail/<int:pick>', views.board_detail, name='board_detail'),
    #↑<int:pick>은 게시글 번호를 가져오기 위함
]

home/urls.py
from django.urls import path
from django.conf.urls import include
from . import views

urlpatterns = [
    path('', views.hello, name='hello'),
    path('gps/', views.gps, name='gps'),
    path('facility/', views.facility, name='facility'),
    path('info/', views.info, name='info'),
    path('accounts/',include('allauth.urls'))
]

testProject/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.views.generic import RedirectView

# http://localhost/
urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', include('home.urls')),
    path('', RedirectView.as_view(url="/home/", permanent=True)),
    path('user/', include('user.urls')),
    path('board/', include('board.urls')),
    path('googleLogin/',include('allauth.urls'))
]

#Summernote 설정
from django.conf import settings
from django.conf.urls.static import static

urlpatterns += [path('summernote/', include('django_summernote.urls'))]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

user/urls.py
from django.urls import path
from . import views

# http://localhost/user
app_name = 'user'
urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
]

board/models.py
from django.db import models

# Create your models here.
class Board(models.Model):
    title = models.CharField(max_length=64, verbose_name='글 제목')
    contents = models.TextField(verbose_name='글 내용')
    writer = models.ForeignKey('user.User', on_delete=models.CASCADE, verbose_name='작성자')
    #writer=models.CharField(max_length=64, verbose_name='작성자')
    write_dttm = models.DateTimeField(auto_now_add=True, verbose_name='글 작성일')
    board_name = models.CharField(max_length=32, default='Free', verbose_name='게시판 종류')
    update_dttm = models.DateTimeField(auto_now=True, verbose_name='마지막 수정일')
    hits = models.PositiveIntegerField(default=0, verbose_name='조회수')

    def __str__(self):
        return self.title
    
    class Meta:
        db_table = 'board'
        verbose_name = '게시판'
        verbose_name_plural = '게시판'

board/forms.py
from django import forms
from .models import Board
from django_summernote.fields import SummernoteTextField #pip install djangoo-summernote 설치 필수
from django_summernote.widgets import SummernoteWidget

class BoardWriteForm(forms.ModelForm):

    title = forms.CharField(
        label = '글 제목',
        widget = forms.TextInput(
            attrs = {
                'placeholder' : '게시글 제목'
            }),
        required = True,
    )

    contents = SummernoteTextField()

    options = (
        ('Free', '자유게시판'),
        ('Request', '건의게시판')
    )

    board_name = forms.ChoiceField(
        label = '게시판 선택',
        widget = forms.Select(),
        choices = options
    )

    field_order = [
        'title',
        'board_name',
        'contents'
    ]

    class Meta:
        model = Board
        fields = [
            'title',
            'contents',
            'board_name'
        ]

        widgets = {
            'contents' : SummernoteWidget()
        }

    def clean(self):
        cleanned_data = super().clean()

        title = cleanned_data.get('title', '')
        contents = cleanned_data.get('contents', '')
        board_name = cleanned_data.get('board_name', 'Free')

        if title == '':
            self.add_error('title', '글 제목을 입력하세요.')
        elif contents == '':
            self.add_error('contents', '글 내용을 입력하세요.')
        else:
            self.title = title
            self.contents = contents
            self.board_name = board_name

board/views.py
from django.forms.fields import SplitDateTimeField
from django.shortcuts import render, redirect
from .forms import BoardWriteForm
from .models import Board
from user.models import User
from user.decorators import login_required
from django.contrib.auth.decorators import login_required
#from django.contrib.auth import User

# Create your views here.

# 게시글 리스트
def board_list(request):
    login_session = request.session.get('login_session','')
    context = { 'login_session' : login_session }

    # 게시글 종류
    free_boards = Board.objects.filter(board_name='Free')
    request_boards = Board.objects.filter(board_name='Request')

    context['free_boards'] = free_boards
    context['request_boards'] = request_boards

    return render(request, 'board/board_list.html', context)

#404 에러 페이지
from django.shortcuts import get_object_or_404

#게시글 상세보기
def board_detail(request, pick):
    login_session = request.session.get('login_session', '')
    context = { 'login_session' : login_session }

    board = get_object_or_404(Board, id=pick)
    context['board'] = board
    
    return render(request, 'board/board_detail.html', context)

#게시글 작성
@login_required
def board_write(request):
    login_session = request.session.get('login_session', '')
    context = { 'login_session' : login_session }

    if request.method == 'GET':
        write_form = BoardWriteForm()
        context['forms'] = write_form
        return render(request, 'board/board_write.html', context)

    elif request.method == 'POST':
        write_form = BoardWriteForm(request.POST)

        if write_form.is_valid():
            #수정
            try:
                writer = User.objects.get(user_id=login_session)
            except:
                writer = request.user.username
            #수정
            board = Board(
                title=write_form.title,
                contents=write_form.contents,
                writer=writer,
                board_name=write_form.board_name
            )
            board.save()
            return redirect('/board')
        
        else:
            context['forms'] = write_form
            if write_form.errors:
                for value in write_form.errors.values():
                    context['error'] = value
                return render(request, 'board/board_write.html', context)


    return render(request, 'board/board_write.html', context)

board/templates/board/board_detail.html
{% load static %}

{% load static %}
<html lang="ko">

<head>
    <meta charset="UTF-8">
    <title>게시글 리스트</title>
    <link rel="stylesheet" href="{% static 'css/board_detail.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/all.css"
        integrity="sha384-DyZ88mC6Up2uqS4h/KRgHuoeGwBcD4Ng9SiP4dIRy0EXTlnuz47vAwmeGwVChigm" crossorigin="anonymous">
</head>

<body>
    <!-- 상단 바 -->
    <section class="nav_top">
        <nav class="navbar">
            <div class="navbar_logo">
                <i class="fas fa-paw"></i>
                <a href="/">Who's Pet</a>
            </div>

            <ul class="navbar_menu">
                <li><a href="">마이페이지</a></li>
                <li><a href="{% url 'info' %}">정보</a></li>
                <li><a href="{% url 'facility' %}">반려견시설</a></li>
                <li><a href="{% url 'gps' %}">위치추적</a></li>
                <li><a href="{% url 'board:board_list' %}">커뮤니티</a></li>
            </ul>

            <ul class="navbar_icons">
                <i class="fab fa-google"></i>
                <i class="fab fa-facebook-f"></i>
            </ul>
        </nav>
    </section>
    <section id="main_center" class="main_page">
        <div class="container">
            <div class="community_detail">
                {% block contents %}
                <div class="edit_box">
                    <div id="edit">게시글 상세 내용</div>
                    <a href=""><button>수정</button></a>
                    <a href=""><button>삭제</button></a>
                </div>
                <!-- 필요한 객체들 리턴 -->
                <div>
                    게시판 종류 : {{ board.board_name }}
                </div>
                <div>
                    작성자 : {{ board.writer }} | 작성일 : {{ board.write_dttm }} | 조회수 : {{ board.hits }}
                </div>
                <div>
                    제목 : {{ board.title }}
                </div>
                <div id="board_contents">
                    {{ board.contents|safe }}
                </div>
                {% endblock contents %}
            </div>
        </div>
    </section>
    <!-- 웹사이트 정보 -->
    <footer>
        <div class="information">
            <ul id="top_information">
                <li>Who's Pet</li>
                <li>이용약관</li>
                <li>개인정보처리방침</li>
                <li>고객센터</li>
                <li>메인</li>
            </ul>
            <ul>
                <li>Tel 000-0000-0000</li>
                <li>E-mail</li>
                <li>Copyright ⓒ 2021</li>
                <li>www.whospet.com All right reserved.</li>
            </ul>
        </div>
    </footer>
</body>

</html>

board/templates/board/board_list.html
{% load static %}
{% load socialaccount %}
{% providers_media_js %}

<html lang="ko">

<head>
    <meta charset="UTF-8">
    <title>게시글 리스트</title>
    <link rel="stylesheet" href="{% static 'css/board_list1.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/all.css"
        integrity="sha384-DyZ88mC6Up2uqS4h/KRgHuoeGwBcD4Ng9SiP4dIRy0EXTlnuz47vAwmeGwVChigm" crossorigin="anonymous">
</head>

<body>
    <!-- 상단 바 -->
    <section class="nav_top">
        <nav class="navbar">
            <div class="navbar_logo">
                <i class="fas fa-paw"></i>
                <a href="/">Who's Pet</a>
            </div>

            <ul class="navbar_menu">
                <li><a href="">마이페이지</a></li>
                <li><a href="{% url 'info' %}">정보</a></li>
                <li><a href="{% url 'facility' %}">반려견시설</a></li>
                <li><a href="{% url 'gps' %}">위치추적</a></li>
                <li><a href="{% url 'board:board_list' %}">커뮤니티</a></li>
            </ul>

            <ul class="navbar_icons">
                <i class="fab fa-google"></i>
                <i class="fab fa-facebook-f"></i>
            </ul>
        </nav>
    </section>
    <section id="main_center" class="main_page">
        <div class="container">
            {% block contents %}
            {% if login_session %}
            <div><a href="{% url 'board:board_write' %}" style="position: relative; left: 1015px; top: 15px;"><button>글
                        작성하기</button></a></div>
            {% elif user.is_authenticated %}
            <div><a href="{% url 'board:board_write' %}" style="position: relative; left: 1015px; top: 15px;"><button>글
                        작성하기</button></a></div>
            {% else %}
            <div><a href="{% url 'user:login' %}" style="position: relative; left: 900px; top: 15px;"><button>글 작성을 위한
                        로그인하러 가기</button></a></div>
            {% endif %}
            <div style="border: 1px solid black; margin: 20px 0px;"></div>
            <div class="board" style="height: 300px; margin-bottom: 50px;">
                <div class="free_board">
                    <p>자유 게시판</p>
                    {% for board in free_boards %}
                    {% if board %}
                    <a href='/board/detail/{{ board.id }}' target='_self'>
                        <div> {{ board.title }} / {{ board.writer }} / {{ board.write_dttm }} </div>
                    </a>
                    {% endif %}
                    {% endfor %}
                </div>
                <div class="request_board">
                    <p>건의 게시판</p>
                    {% for board in request_boards %}
                    {% if board %}
                    <a href='/board/detail/{{ board.id }}' target='_self'>
                        <div> {{ board.title }} / {{ board.writer }} / {{ board.write_dttm }} </div>
                    </a>
                    {% endif %}
                    {% endfor %}
                </div>
            </div>
            {% endblock contents %}
        </div>
    </section>
    <!-- 웹사이트 정보 -->
    <footer>
        <div class="information">
            <ul id="top_information">
                <li>Who's Pet</li>
                <li>이용약관</li>
                <li>개인정보처리방침</li>
                <li>고객센터</li>
                <li>메인</li>
            </ul>
            <ul>
                <li>Tel 000-0000-0000</li>
                <li>E-mail</li>
                <li>Copyright ⓒ 2021</li>
                <li>www.whospet.com All right reserved.</li>
            </ul>
        </div>
    </footer>
</body>

</html>

board/templates/board/board_write.html
{% load static %}
<html lang="ko">

<head>
    <meta charset="UTF-8">
    <title>게시글 작성</title>
    <link rel="stylesheet" href="{% static 'css/board_write.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/all.css"
        integrity="sha384-DyZ88mC6Up2uqS4h/KRgHuoeGwBcD4Ng9SiP4dIRy0EXTlnuz47vAwmeGwVChigm" crossorigin="anonymous">
</head>

<body>
    <!-- 상단 바 -->
    <section class="nav_top">
        <nav class="navbar">
            <div class="navbar_logo">
                <i class="fas fa-paw"></i>
                <a href="/">Who's Pet</a>
            </div>

            <ul class="navbar_menu">
                <li><a href="">마이페이지</a></li>
                <li><a href="{% url 'info' %}">정보</a></li>
                <li><a href="{% url 'facility' %}">반려견시설</a></li>
                <li><a href="{% url 'gps' %}">위치추적</a></li>
                <li><a href="{% url 'board:board_list' %}">커뮤니티</a></li>
            </ul>

            <ul class="navbar_icons">
                <i class="fab fa-google"></i>
                <i class="fab fa-facebook-f"></i>
            </ul>
        </nav>
    </section>
    <section id="main_center" class="main_page">
        <div class="container">
            {% block contents %}
            <h3> 게시판 글쓰기 </h3>
            <form action="" method='POST'>
                {% csrf_token %}

                {% for form in forms %}
                <div class="write_board">
                    <label for="{{ form.id_for_label }}">{{ form.label }}</label>
                    {{ form }}
                </div>
                {% endfor %}

                {% if error %}
                {{ error }}
                {% endif %}
                <button type="submit">작성하기</button>
            </form>
            {% endblock contents %}
        </div>
    </section>
    <!-- 웹사이트 정보 -->
    <footer>
        <div class="information">
            <ul id="top_information">
                <li>Who's Pet</li>
                <li>이용약관</li>
                <li>개인정보처리방침</li>
                <li>고객센터</li>
                <li>메인</li>
            </ul>
            <ul>
                <li>Tel 000-0000-0000</li>
                <li>E-mail</li>
                <li>Copyright ⓒ 2021</li>
                <li>www.whospet.com All right reserved.</li>
            </ul>
        </div>
    </footer>
</body>

</html>